[package]
name = "mainline-network-test"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.46.1", features = ["net", "time", "rt-multi-thread", "macros", "sync"] }

[[bin]]
name = "sync"
path = "src/sync.rs"

[[bin]]
name = "async"
path = "src/async.rs"